# Generated by Django 4.2 on 2026-05-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_peliculas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='movies_pictures/'),
        ),
    ]
